[Variables]
; Work Settings
WorkStartHour=8
WorkTotalHours=8
WorkHideOnWeekends=1
WorkTextWhenHidden=work: off
; Text Settings
TextDecimalPlaces=1
; Try: AvantGarde BK Bt, Cascadia Mono, Courier New, Ink Free
; May have to adjust BarOffset between 1 - 1.75 to make bars align correctly
TextFont=AvantGarde BK Bt
TextWeight=100
TextColor=222,222,222,255
TextSize=30
TextGap=32
; Bar Settings
BarHeight=5
BarWidth=328
BarBGColor=120,120,120,220
BarFillColor=255,255,255,220
BarYGap=46
BarOffset=1.5